name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  ideal-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check Gradle build environment
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildEnvironment
          build-root-directory: ideal-case
  workaround-case-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check Gradle build environment
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildEnvironment
          build-root-directory: workaround-case-1
